namespace EstoqueService
{
    public static class Estoque
    {
        public static readonly Dictionary<string, int> EstoqueProdutos = new Dictionary<string, int>
        {
            { "maçã", 150 },
            { "banana", 250 },
            { "laranja", 50 },
            { "uva", 75 },
            { "tomate", 100 },
            { "batata", 120 },
            { "cenoura", 90 },
            { "brócolis", 80 },
            { "peito de frango", 30 },
            { "bife de carne", 60 },
            { "costeleta de porco", 200 },
            { "filé de salmão", 140 },
            { "leite", 300 },
            { "ovos", 500 },
            { "queijo", 250 },
            { "iogurte", 180 },
            { "arroz", 1000 },
            { "feijão", 800 },
            { "macarrão", 600 },
            { "pão", 450 },
            { "azeite de oliva", 100 },
            { "manteiga", 90 },
            { "café", 200 },
            { "açúcar", 350 },
            { "sal", 400 },
            { "farinha de trigo", 500 },
            { "fermento", 80 },
            { "chocolate", 150 },
            { "bolacha", 300 },
            { "cereal", 250 },
            { "granola", 100 },
            { "mel", 75 },
            { "chá", 60 },
            { "suco de laranja", 120 },
            { "água mineral", 1000 },
            { "refrigerante", 500 },
            { "cerveja", 400 },
            { "vinho", 200 },
            { "whisky", 100 },
            { "vodka", 90 },
            { "rum", 80 },
            { "tequila", 70 },
            { "gin", 60 },
            { "desinfetante", 150 },
            { "detergente", 200 },
            { "sabão em pó", 180 },
            { "amaciante", 120 },
            { "shampoo", 250 },
            { "condicionador", 200 },
            { "sabonete", 300 },
            { "creme dental", 400 },
            { "escova de dentes", 350 },
            { "desodorante", 150 },
            { "perfume", 100 },
            { "creme hidratante", 120 },
            { "protetor solar", 90 },
            { "repelente", 80 },
            { "fralda", 200 },
            { "lenço umedecido", 300 },
            { "papel higiênico", 500 },
            { "guardanapo", 400 },
            { "toalha de papel", 250 },
            { "sacola plástica", 600 },
            { "luva de borracha", 100 },
            { "pano de prato", 150 },
            { "esponja de limpeza", 200 },
            { "rodo", 80 },
            { "vassoura", 70 },
            { "pá de lixo", 90 },
            { "balde", 100 },
            { "mop", 60 },
            { "saco de lixo", 500 },
            { "cloro", 150 },
            { "água sanitária", 180 }
        };
    }
}
